// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_master_of_the_night = "CgkI5dPLwvQKEAIQBg"; // <GPGSID>
        public const string achievement_master_of_dodgers = "CgkI5dPLwvQKEAIQDw"; // <GPGSID>
        public const string achievement_first_time = "CgkI5dPLwvQKEAIQAQ"; // <GPGSID>
        public const string achievement_owner_of_the_night = "CgkI5dPLwvQKEAIQBQ"; // <GPGSID>
        public const string achievement_master_of_ice = "CgkI5dPLwvQKEAIQCQ"; // <GPGSID>
        public const string achievement_player_of_midnight = "CgkI5dPLwvQKEAIQCw"; // <GPGSID>
        public const string achievement_player_of_midday = "CgkI5dPLwvQKEAIQDA"; // <GPGSID>
        public const string achievement_master_of_fire = "CgkI5dPLwvQKEAIQCg"; // <GPGSID>
        public const string achievement_owner_of_the_day = "CgkI5dPLwvQKEAIQBw"; // <GPGSID>
        public const string achievement_master_strategist = "CgkI5dPLwvQKEAIQEQ"; // <GPGSID>
        public const string achievement_player_of_the_day = "CgkI5dPLwvQKEAIQAw"; // <GPGSID>
        public const string achievement_raining_day_isnt_it = "CgkI5dPLwvQKEAIQDQ"; // <GPGSID>
        public const string achievement_player_of_the_night = "CgkI5dPLwvQKEAIQBA"; // <GPGSID>
        public const string achievement_big_strategist = "CgkI5dPLwvQKEAIQEA"; // <GPGSID>
        public const string leaderboard_global_leaderboard = "CgkI5dPLwvQKEAIQAg"; // <GPGSID>
        public const string achievement_big_dodger = "CgkI5dPLwvQKEAIQDg"; // <GPGSID>
        public const string achievement_master_of_the_day = "CgkI5dPLwvQKEAIQCA"; // <GPGSID>

}

